# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/CodingProjects/RTLProject/LTS-SiringCPU/vivado/SiringCPU.srcs/sources_1/ip/UART_window/UART_window.xci
# IP: The module: 'UART_window' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CodingProjects/RTLProject/LTS-SiringCPU/vivado/SiringCPU.srcs/sources_1/ip/UART_window/UART_window_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_window'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/CodingProjects/RTLProject/LTS-SiringCPU/vivado/SiringCPU.srcs/sources_1/ip/UART_window/UART_window.xci
# IP: The module: 'UART_window' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CodingProjects/RTLProject/LTS-SiringCPU/vivado/SiringCPU.srcs/sources_1/ip/UART_window/UART_window_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'UART_window'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
